[package]
name = "rlc"
version = "0.1.0"
authors = ["Aaron Dandy <aaron.dandy@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2"
failure = "0.1.8"
exitfailure = "0.5.1"
structopt = "0.3"
